name: "Build and push docker image"
description: "Builds and pushes a docker image to a registry with caching"

inputs:
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  docker_image_name:
    description: "Docker image name"
    required: true
  release_version:
    description: "Release version"
    required: false
    default: "0.0.0"

outputs:
  image:
    description: "Docker image name with tag"
    value: ${{ steps.set_output.outputs.image }}

runs:
  using: "composite"

  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push with Cache
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.docker_image_name }}:${{ inputs.release_version }}
        build-args: |
          VERSION=${{ inputs.release_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set output variables
      id: set_output
      shell: bash
      run: |
        echo "image=${{ inputs.docker_image_name }}:${{ inputs.release_version }}" >> $GITHUB_OUTPUT
