name: Scheduled Base Image Updates

on:
  schedule:
    # Run every Sunday at 2 AM UTC to rebuild with latest base images
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  rebuild-latest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Generate timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image with latest base
      id: build
      uses: your-username/build-push-image@v1
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_image_name: myorg/myapp
        release_version: nightly-${{ steps.timestamp.outputs.TIMESTAMP }}
    
    - name: Also update latest tag
      uses: your-username/build-push-image@v1
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_image_name: myorg/myapp
        release_version: latest
    
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Scheduled build failed on ' + new Date().toISOString().split('T')[0],
            body: `The scheduled Docker image build failed.
            
            **Workflow:** ${context.workflow}
            **Run ID:** ${context.runId}
            **Commit:** ${context.sha}
            
            Please check the [workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['bug', 'scheduled-build']
          })